import { Eye, LifeBuoy, UsersRound } from 'lucide-react';
import { ASSETS } from '../content';
import { useSiteExperience } from '../siteExperience';
import { SectionHeading } from './SectionHeading';

const media=[
  {image:ASSETS.fieldReadiness,width:960,height:1280,icon:Eye},
  {image:ASSETS.fieldTeam,width:960,height:1280,icon:UsersRound},
  {image:ASSETS.fieldIdentity,width:596,height:525,icon:LifeBuoy},
] as const;
export function FieldOperations(){const {copy}=useSiteExperience(); const c=copy.field; return <section id="field-operations" className="relative w-full overflow-hidden border-b border-corp-border/40 bg-corp-navy py-16 sm:py-20 lg:py-28"><div className="relative mx-auto flex max-w-7xl flex-col gap-12 px-5 sm:px-8"><div className="grid gap-8 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><SectionHeading index="08" label={c.label} title={<>{c.titleA}<br/><span className="text-corp-sand">{c.titleB}</span></>} description={c.description}/></div><div data-reveal="up" data-delay="80" className="lg:col-span-4"><p className="field-side-note border-s-2 border-corp-blue ps-4 text-sm leading-7 text-slate-300">{c.sideNote}</p></div></div><div className="grid grid-cols-1 gap-4 md:grid-cols-12">{c.items.map(([alt,title,label],index)=>{const item=media[index]; const Icon=item.icon; const cls=index===0?'md:col-span-7':index===1?'md:col-span-5':'md:col-span-12'; return <article key={`field-operation-${index}`} data-reveal="image" data-delay={String(index*70)} className={`field-card group relative min-h-[360px] overflow-hidden rounded-[24px] border border-corp-border bg-corp-navy-dark ${cls} ${index===2?'md:min-h-[310px]':'md:min-h-[520px]'}`}><img src={item.image} width={item.width} height={item.height} alt={alt} className={`absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.025] ${index===2?'object-center':'object-[50%_42%]'}`} loading="lazy" decoding="async"/><div className="media-shade absolute inset-0 bg-gradient-to-t from-corp-navy-dark via-corp-navy-dark/20 to-transparent" aria-hidden="true"/><div className="media-overlay absolute inset-x-0 bottom-0 flex items-end justify-between gap-5 p-5 sm:p-6"><div><span className="font-inter text-[9px] font-bold uppercase tracking-[0.17em] text-corp-sand">{label}</span><h3 className="font-cairo mt-1 text-xl font-black text-white sm:text-2xl">{title}</h3></div><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-white/15 bg-corp-navy-dark/75 text-corp-sea backdrop-blur-md" aria-hidden="true"><Icon className="h-5 w-5"/></span></div></article>})}</div></div></section>}
