import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const textExtensions = new Set(['.ts','.tsx','.css','.html','.json','.md','.txt']);
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const f=path.join(dir,e.name);if(['node_modules','dist'].includes(e.name))return[];if(e.isDirectory())return walk(f);return textExtensions.has(path.extname(e.name))?[f]:[]})}
const files=walk(root); const srcFiles=walk(path.join(root,'src')); const source=srcFiles.map(f=>fs.readFileSync(f,'utf8')).join('\n');
const indexHtml=fs.readFileSync(path.join(root,'index.html'),'utf8'); const productionText=source+'\n'+indexHtml;
const i18n=fs.readFileSync(path.join(root,'src','i18n.ts'),'utf8'); const app=fs.readFileSync(path.join(root,'src','App.tsx'),'utf8');
const viteConfig=fs.readFileSync(path.join(root,'vite.config.ts'),'utf8');
const liveGate=fs.readFileSync(path.join(root,'.github','workflows','live-production-gate.yml'),'utf8');
const failures=[]; const pass=(c,m)=>{if(!c)failures.push(m)};

for(const value of ['01280033504','01061950609','v.east000@gmail.com','201280033504','إدارة وتشغيل المنشآت الرياضية','الإشراف والمتابعة والتقييم الميداني','Sports facility management & operations','Field supervision, follow-up & evaluation']) pass(productionText.includes(value),`Missing approved/localized content: ${value}`);
for(const value of ['V.EAST HEADQUARTERS','HEADQUARTERS','Gemini','Google AI Studio','@google/genai','GEMINI_API_KEY','Powered by AI','Generated by AI','Midjourney','Stable Diffusion','contact@veast-operations.com','201000000000','كوادر معتمدة']) pass(!productionText.includes(value),`Forbidden/unsupported residue found: ${value}`);

pass(/<html[^>]*lang="ar"[^>]*dir="rtl"[^>]*data-theme="dark"/.test(indexHtml),'Initial document must be Arabic RTL with a dark fallback before preference hydration.');
pass(indexHtml.includes("localStorage.getItem('veast-theme')")&&indexHtml.includes("localStorage.getItem('veast-language')"),'Pre-paint theme/language restoration is required.');
pass(source.includes("root.lang = language")&&source.includes("root.dir = language === 'ar' ? 'rtl' : 'ltr'"),'Runtime language must update lang and dir.');
pass(source.includes("root.dataset.theme = theme")&&source.includes("window.localStorage.setItem('veast-theme', theme)"),'Theme state must be real and persisted.');
pass(!source.includes("startViewTransition")&&source.includes("preserveRevealState();")&&source.includes("setThemeState(next);"),'Theme switching must avoid stale browser view-transition layers while preserving reveal state.');
pass(source.includes("window.dispatchEvent(new Event('resize'))"),'Theme/language switching must force measured UI to reflow after experience changes.');
pass(productionText.includes('Final hardening: light-mode contrast + mobile media safety')&&productionText.includes('.hero-section .hero-field-card')&&productionText.includes('position: relative !important'),'Final light-mode contrast and mobile overlap hardening must remain present.');
pass(source.includes('theme-scene-toggle')&&source.includes('ThemeSceneToggle'),'Animated day/night theme control must be implemented.');
pass(source.includes('LanguageToggle')&&source.includes("setLanguage('ar')")&&source.includes("setLanguage('en')"),'Both Arabic and English controls must be implemented.');
pass(i18n.includes("ar: {")&&i18n.includes("en: {")&&i18n.includes("facilities:")&&i18n.includes("places:"),'Central translation catalog must contain Arabic and English content, including the featured places section.');

for(const file of srcFiles.filter(f=>f.endsWith('.tsx')&&!f.endsWith('siteExperience.tsx'))){if(file.endsWith('i18n.tsx'))continue;const text=fs.readFileSync(file,'utf8');if(path.basename(file)!=='ExperienceControls.tsx')pass(!/[\u0600-\u06FF]/.test(text),`Hardcoded Arabic UI copy outside i18n: ${path.relative(root,file)}`)}
pass((source.match(/<h1\b/g)??[]).length===1,'Exactly one H1 is required.');
for(const token of ['sm:','md:','lg:','xl:']) pass(source.includes(token),`Missing responsive breakpoint ${token}`);
pass(source.includes('aria-expanded')&&source.includes('aria-controls'),'Accessible disclosure/menu state attributes are required.');
pass(source.includes('FeaturedPlaces')&&source.includes('id="places"'),'Featured places section must be mounted in the application.');
pass(source.includes('aria-haspopup="dialog"')&&source.includes('role="dialog"')&&source.includes('aria-modal="true"'),'Featured place cards must open into an accessible dialog.');
pass(source.includes('createPortal')&&source.includes("shell.setAttribute('inert', '')")&&source.includes("event.key === 'Escape'")&&source.includes("event.key !== 'Tab'"),'Featured place dialog must portal outside the app shell, isolate background content and support Escape/Tab focus handling.');
pass(source.includes('aria-modal="true"')&&source.includes('inert={!open}'),'Mobile drawer must remain modal and inert while closed.');
pass(source.includes('contact.focus({ preventScroll: true })'),'Contact CTA must preserve keyboard focus continuity.');
pass(source.includes('aria-current={active?\'location\':undefined}')||source.includes("aria-current={active?'location':undefined}"),'Active navigation must expose aria-current.');

for(const asset of ['veast-logo.webp','office-wall-brand.webp','hero-field.webp','operations-portfolio.webp','field-team-01.webp','field-team-02.webp','uniform-brand.webp','elite-beach-logo.webp','half-moon-profile.webp']) pass(fs.existsSync(path.join(root,'public','assets',asset)),`Missing local asset: ${asset}`);
const imgs=[...source.matchAll(/<img\b[^>]*>/g)].map(m=>m[0]); pass(imgs.length>=7,'Expected local imagery is missing.'); imgs.forEach((tag,i)=>pass(/\bwidth=/.test(tag)&&/\bheight=/.test(tag),`Image ${i+1} missing intrinsic size.`));
pass(!/src="https?:\/\//i.test(source),'Production image sources must remain local.');
for(const tag of [...source.matchAll(/<a\b[^>]*target="_blank"[^>]*>/g)].map(m=>m[0])) pass(/rel="noopener noreferrer"/.test(tag),'Every target=_blank link must use noopener noreferrer.');

const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')); const deps=new Set([...Object.keys(pkg.dependencies??{}),...Object.keys(pkg.devDependencies??{})]);
for(const dep of ['@google/genai','express','dotenv','motion','framer-motion']) pass(!deps.has(dep),`Unnecessary dependency present: ${dep}`);
pass(indexHtml.includes('type="application/ld+json"')&&indexHtml.includes('property="og:image"')&&indexHtml.includes('twitter:card'),'SEO/social/structured metadata foundation must remain present.');
pass(source.includes('setMeta(\'meta[name="description"]\'')&&source.includes('meta[property="og:locale"]'),'Localized metadata must update with language.');
pass(source.includes('useScrollReveal')&&source.includes('data-reveal="image"'),'Content-linked reveal motion must remain wired.');
pass(viteConfig.includes("name: 'veast-release'")&&viteConfig.includes('VERCEL_GIT_COMMIT_SHA')&&viteConfig.includes('VEAST_RELEASE_SHA'),'Build must embed an auditable release fingerprint with Vercel/GitHub override support.');
pass(liveGate.includes('Verify exact deployed commit fingerprint and security headers')&&liveGate.includes('EXPECTED_MAIN=')&&liveGate.includes('LIVE_RELEASE=')&&liveGate.includes('PASS live security headers'),'Live production gate must reject stale Vercel deployments and missing security headers.');
pass(productionText.includes('@media (prefers-reduced-motion: reduce)'),'Reduced-motion CSS is required.');
pass(!/animation\s*:[^;]*infinite/i.test(productionText),'Decorative infinite animation is forbidden.');
pass(!/will-change\s*:/i.test(productionText),'Persistent will-change is forbidden.');
pass(!/filter\s*:\s*saturate/i.test(productionText),'Animated saturation/filter effect is forbidden.');

if(failures.length){console.error(`Source verification failed (${failures.length} issues):`);failures.forEach(f=>console.error(`- ${f}`));process.exit(1)}
console.log(`Source verification passed (${files.length} text files checked; bilingual + dual-theme gates active).`);
